In [1]:
#! pip install cv2 -- user
# pip install imutils

In [1]:
# Import Library
import cv2 
import imutils
import numpy as np 

In [2]:
image = cv2.imread(r"C:\Users\pcc\Desktop\DSC_3073.JPG")
print(image)  # Print the image array

[[[185 192 201]
  [185 192 201]
  [186 193 202]
  ...
  [198 204 211]
  [198 204 209]
  [195 204 207]]

 [[187 194 203]
  [187 194 203]
  [187 194 203]
  ...
  [198 204 211]
  [196 202 207]
  [195 204 207]]

 [[187 194 203]
  [187 194 203]
  [188 195 204]
  ...
  [197 203 208]
  [197 203 210]
  [197 204 207]]

 ...

 [[169 173 178]
  [171 173 183]
  [169 172 180]
  ...
  [172 174 184]
  [171 176 185]
  [171 177 184]]

 [[173 175 183]
  [171 173 181]
  [170 172 182]
  ...
  [170 175 184]
  [170 175 184]
  [168 176 183]]

 [[172 174 182]
  [172 174 182]
  [169 171 181]
  ...
  [171 176 185]
  [168 175 184]
  [168 176 183]]]


In [2]:
image=cv2.imread(r"C:\Users\pcc\Desktop\DSC_3073.JPG")
if image is not None:
    image=cv2.resize(image,(500,500))
    cv2.imshow("Image",image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
else:
    print("Image not loaded properly.")

In [20]:
# Rotate image using "rotate"
for angle in np.arange(0,360,15):
    rotated=imutils.rotate(image,angle)
    cv2.imshow("Rotated_image",rotated)
    cv2.waitKey(0)

In [4]:
# Rotate image using "rotate_bound"
for angle in np.arange(0,360,15):   # 15 degree increment
    rotated=imutils.rotate_bound(image,angle)
    cv2.imshow("rotated",rotated)
    cv2.waitKey(3000)
    

In [10]:
# Image rotation founction that oesn't cut off image

def rotate_bound(image, angle):
    # grab dimensions and center of image
    (h,w)=image.shape[:2]
    (cx,cy)=(w//2,h//2)
    
    # calculate rotation matrix
    M= cv2.getRotationMatrix2D((cx,cy),angle,1)
    cos=np.abs(M[0,0])
    sin=np.abs(M[0,1])
    
    # new bounding dimensions
    nw=int((h*sin)+(w*cos))
    nh=int((h*cos)+(w*sin))
    
    # adjust rotation matrix
    M[0,2] +=(nw/2)-cx
    M[1,2]+=(nh/2)-cy
    
    # perform actural rotation
    return cv2.warpAffine(image, M, (nw,nh))

In [17]:
angle=(360)
rotate_bound(image,angle)

array([[[189, 196, 205],
        [193, 199, 208],
        [196, 201, 210],
        ...,
        [197, 204, 207],
        [199, 203, 208],
        [196, 204, 206]],

       [[193, 201, 210],
        [198, 204, 213],
        [197, 206, 215],
        ...,
        [199, 204, 207],
        [199, 203, 208],
        [198, 202, 207]],

       [[198, 203, 212],
        [201, 204, 215],
        [200, 206, 217],
        ...,
        [198, 204, 207],
        [200, 205, 208],
        [198, 203, 206]],

       ...,

       [[153, 159, 166],
        [151, 157, 165],
        [149, 157, 164],
        ...,
        [174, 178, 185],
        [173, 179, 185],
        [174, 180, 186]],

       [[161, 167, 175],
        [157, 164, 171],
        [155, 163, 171],
        ...,
        [173, 176, 185],
        [174, 177, 185],
        [176, 176, 185]],

       [[167, 170, 178],
        [167, 170, 181],
        [166, 169, 177],
        ...,
        [173, 176, 184],
        [174, 177, 186],
        [173, 177, 185]]

In [3]:
# fixing the rotated image "cut off" problem with opencv and python

gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
gray=cv2.GaussianBlur(gray,(3,3),0)
edge=cv2.Canny(gray,20,100)
cv2.imshow("a",edge)
cv2.waitKey(0)

-1

In [4]:
# find the comtours in the edge map

cnts=cv2.findContours(edge.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
cnts=imutils.grab_contours(cnts)

In [5]:
if len(cnts)>0:
    c=max(cnts,key=cv2.contourArea)
    mask=np.zeros(gray.shape,dtype="uint8")
    cv2.drawContours(mask,[c],-1,255,-1)
    
    (x,y,w,h)=cv2.boundingRect(c)
    imageROI=image[y:y+h,x:x+w]
    maskROI= mask[y:y+h,x:x+w]
    imageROI=cv2.bitwise_and(imageROI,imageROI,mask=maskROI)

In [55]:
cv2.imshow("a",imageROI)
cv2.waitKey(0)

-1

In [56]:
for angle in np.arange(0,360,15):
    rotated= imutils.rotate(imageROI,angle)
    cv2.imshow("image",rotated)
    cv2.waitKey(3000)

In [6]:
for angle in np.arange(0,360,15):
    rotated= imutils.rotate_bound(imageROI,angle)
    cv2.imshow("image",rotated)
    cv2.waitKey(1000)